
spring:
  datasource:
    url: jdbc:h2:mem:reward
    driver-class-name: org.h2.Driver
    username: h2
    password: h2
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080